[package]
org="ballerinax"
name="postgresql.driver"
version="1.2.0"
authors=["Ballerina"]
keywords=["PostgreSQL"]
repository="https://github.com/ballerina-platform/module-ballerinax-postgresql.driver"
license=["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.3.3"
